// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { endpoints, type EndpointOperation, type EndpointPathParam, type RequestByOperation, type ResponseByOperation } from "./endpoints.js";
import type { ContractTransport, ContractTransportRequest } from "./transport.js";

type ClientRequestShape = object;

export type ContractsClient = {
  [Operation in EndpointOperation]: (request: RequestByOperation[Operation]) => Promise<ResponseByOperation[Operation]>;
};

export function createContractsClient(transport: ContractTransport): ContractsClient {
  return {
    createDir: (request) => executeOperation("createDir", request, transport),
    createFile: (request) => executeOperation("createFile", request, transport),
    getNodeByPath: (request) => executeOperation("getNodeByPath", request, transport),
    nodeExists: (request) => executeOperation("nodeExists", request, transport),
    listRootChildren: (request) => executeOperation("listRootChildren", request, transport),
    getNodeById: (request) => executeOperation("getNodeById", request, transport),
    listChildren: (request) => executeOperation("listChildren", request, transport),
    getNodePath: (request) => executeOperation("getNodePath", request, transport),
    moveNode: (request) => executeOperation("moveNode", request, transport),
    deleteNode: (request) => executeOperation("deleteNode", request, transport),
  };
}

async function executeOperation<Operation extends EndpointOperation>(
  operation: Operation,
  request: RequestByOperation[Operation],
  transport: ContractTransport,
): Promise<ResponseByOperation[Operation]> {
  const endpoint = endpoints[operation];
  const queryString = buildQueryString(endpoint.queryParams, request as ClientRequestShape);
  const path = buildPath(endpoint.pathTemplate, endpoint.pathParams, request as ClientRequestShape) + queryString;
  const body = buildJsonBody(endpoint.pathParams, endpoint.queryParams, endpoint.hasJsonBody, request as ClientRequestShape);
  const transportRequest: ContractTransportRequest = {
    operationName: endpoint.operationName,
    method: endpoint.method,
    path,
    body,
    headers: buildHeaders(endpoint.hasJsonBody),
  };

  return transport.send<ResponseByOperation[Operation]>(transportRequest);
}

function buildPath(
  pathTemplate: string,
  pathParams: readonly EndpointPathParam[],
  request: ClientRequestShape,
): string {
  const requestRecord = request as Record<string, unknown>;
  let path = pathTemplate;

  for (const pathParam of pathParams) {
    const value = requestRecord[pathParam.wireName];

    if (value === undefined || value === null) {
      throw new Error(`missing path parameter ${pathParam.wireName}`);
    }

    path = path.replace(`{${pathParam.wireName}}`, encodeURIComponent(String(value)));
  }

  return path;
}

function buildQueryString(
  queryParams: readonly EndpointPathParam[],
  request: ClientRequestShape,
): string {
  if (queryParams.length === 0) {
    return "";
  }

  const requestRecord = request as Record<string, unknown>;
  const params = new URLSearchParams();

  for (const queryParam of queryParams) {
    const value = requestRecord[queryParam.wireName];

    if (value !== undefined && value !== null) {
      params.set(queryParam.wireName, String(value));
    }
  }

  const queryString = params.toString();
  return queryString === "" ? "" : `?${queryString}`;
}

function buildJsonBody(
  pathParams: readonly EndpointPathParam[],
  queryParams: readonly EndpointPathParam[],
  hasJsonBody: boolean,
  request: ClientRequestShape,
): Record<string, unknown> | undefined {
  if (!hasJsonBody) {
    return undefined;
  }

  const requestRecord = request as Record<string, unknown>;
  const excludedNames = new Set([...pathParams, ...queryParams].map((p) => p.wireName));

  return Object.fromEntries(
    Object.entries(requestRecord).filter(([fieldName]) => !excludedNames.has(fieldName)),
  );
}

function buildHeaders(hasJsonBody: boolean): Record<string, string> {
  const headers: Record<string, string> = {};

  if (hasJsonBody) {
    headers["content-type"] = "application/json";
  }

  return headers;
}
