// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { endpoints, type EndpointOperation, type EndpointPathParam, type RequestByOperation, type ResponseByOperation } from "./endpoints.js";
import type { ContractTransport, ContractTransportRequest } from "./transport.js";

type ClientRequestShape = object;

export type ContractsClient = {
  [Operation in EndpointOperation]: (request: RequestByOperation[Operation]) => Promise<ResponseByOperation[Operation]>;
};

export function createContractsClient(transport: ContractTransport): ContractsClient {
  return {
  };
}

async function executeOperation<Operation extends EndpointOperation>(
  operation: Operation,
  request: RequestByOperation[Operation],
  transport: ContractTransport,
): Promise<ResponseByOperation[Operation]> {
  const endpoint = endpoints[operation];
  const path = buildPath(endpoint.pathTemplate, endpoint.pathParams, request as ClientRequestShape);
  const body = buildJsonBody(endpoint.pathParams, endpoint.hasJsonBody, request as ClientRequestShape);
  const transportRequest: ContractTransportRequest = {
    operationName: endpoint.operationName,
    method: endpoint.method,
    path,
    body,
    headers: buildHeaders(endpoint.hasJsonBody),
  };

  return transport.send<ResponseByOperation[Operation]>(transportRequest);
}

function buildPath(
  pathTemplate: string,
  pathParams: readonly EndpointPathParam[],
  request: ClientRequestShape,
): string {
  const requestRecord = request as Record<string, unknown>;
  let path = pathTemplate;

  for (const pathParam of pathParams) {
    const value = requestRecord[pathParam.wireName];

    if (value === undefined || value === null) {
      throw new Error(`missing path parameter ${pathParam.wireName}`);
    }

    path = path.replace(`{${pathParam.wireName}}`, encodeURIComponent(String(value)));
  }

  return path;
}

function buildJsonBody(
  pathParams: readonly EndpointPathParam[],
  hasJsonBody: boolean,
  request: ClientRequestShape,
): Record<string, unknown> | undefined {
  if (!hasJsonBody) {
    return undefined;
  }

  const requestRecord = request as Record<string, unknown>;
  const pathParamNames = new Set(pathParams.map((pathParam) => pathParam.wireName));

  return Object.fromEntries(
    Object.entries(requestRecord).filter(([fieldName]) => !pathParamNames.has(fieldName)),
  );
}

function buildHeaders(hasJsonBody: boolean): Record<string, string> {
  const headers: Record<string, string> = {};

  if (hasJsonBody) {
    headers["content-type"] = "application/json";
  }

  return headers;
}
