// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  pathParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
};

export type RequestByOperation = {
};

export type ResponseByOperation = {
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
} satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
