// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { CreateDirRequest, CreateDirResponse, CreateFileRequest, CreateFileResponse, DeleteNodeRequest, GetNodeByIdRequest, GetNodeByPathRequest, GetNodePathRequest, GetNodeResponse, GetPathResponse, ListChildrenRequest, ListChildrenResponse, ListRootChildrenRequest, MoveNodeResponse, MoveNodeWithIdRequest, NodeExistsRequest } from "./node.js";
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  pathParams: readonly EndpointPathParam[];
  queryParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
};

export type RequestByOperation = {
  createDir: CreateDirRequest;
  createFile: CreateFileRequest;
  getNodeByPath: GetNodeByPathRequest;
  nodeExists: NodeExistsRequest;
  listRootChildren: ListRootChildrenRequest;
  getNodeById: GetNodeByIdRequest;
  listChildren: ListChildrenRequest;
  getNodePath: GetNodePathRequest;
  moveNode: MoveNodeWithIdRequest;
  deleteNode: DeleteNodeRequest;
};

export type ResponseByOperation = {
  createDir: CreateDirResponse;
  createFile: CreateFileResponse;
  getNodeByPath: GetNodeResponse;
  nodeExists: boolean;
  listRootChildren: ListChildrenResponse;
  getNodeById: GetNodeResponse;
  listChildren: ListChildrenResponse;
  getNodePath: GetPathResponse;
  moveNode: MoveNodeResponse;
  deleteNode: null;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  createDir: {
    operationName: "createDir",
    method: "POST",
    pathTemplate: "/api/nodes/dirs",
    requestType: "CreateDirRequest",
    responseType: "CreateDirResponse",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  createFile: {
    operationName: "createFile",
    method: "POST",
    pathTemplate: "/api/nodes/files",
    requestType: "CreateFileRequest",
    responseType: "CreateFileResponse",
    pathParams: [],
    queryParams: [],
    hasJsonBody: true,
  },
  getNodeByPath: {
    operationName: "getNodeByPath",
    method: "GET",
    pathTemplate: "/api/nodes/by-path",
    requestType: "GetNodeByPathRequest",
    responseType: "GetNodeResponse",
    pathParams: [],
    queryParams: [{ rustFieldName: "path", wireName: "path" }],
    hasJsonBody: false,
  },
  nodeExists: {
    operationName: "nodeExists",
    method: "GET",
    pathTemplate: "/api/nodes/exists",
    requestType: "NodeExistsRequest",
    responseType: "boolean",
    pathParams: [],
    queryParams: [{ rustFieldName: "path", wireName: "path" }],
    hasJsonBody: false,
  },
  listRootChildren: {
    operationName: "listRootChildren",
    method: "GET",
    pathTemplate: "/api/nodes/root/children",
    requestType: "ListRootChildrenRequest",
    responseType: "ListChildrenResponse",
    pathParams: [],
    queryParams: [],
    hasJsonBody: false,
  },
  getNodeById: {
    operationName: "getNodeById",
    method: "GET",
    pathTemplate: "/api/nodes/{id}",
    requestType: "GetNodeByIdRequest",
    responseType: "GetNodeResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    queryParams: [],
    hasJsonBody: false,
  },
  listChildren: {
    operationName: "listChildren",
    method: "GET",
    pathTemplate: "/api/nodes/{id}/children",
    requestType: "ListChildrenRequest",
    responseType: "ListChildrenResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    queryParams: [],
    hasJsonBody: false,
  },
  getNodePath: {
    operationName: "getNodePath",
    method: "GET",
    pathTemplate: "/api/nodes/{id}/path",
    requestType: "GetNodePathRequest",
    responseType: "GetPathResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    queryParams: [],
    hasJsonBody: false,
  },
  moveNode: {
    operationName: "moveNode",
    method: "PUT",
    pathTemplate: "/api/nodes/{id}/move",
    requestType: "MoveNodeWithIdRequest",
    responseType: "MoveNodeResponse",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    queryParams: [],
    hasJsonBody: true,
  },
  deleteNode: {
    operationName: "deleteNode",
    method: "DELETE",
    pathTemplate: "/api/nodes/{id}",
    requestType: "DeleteNodeRequest",
    responseType: "null",
    pathParams: [{ rustFieldName: "id", wireName: "id" }],
    queryParams: [],
    hasJsonBody: false,
  },
} satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
