// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields required to create a new directory node.
 */
export type CreateDirRequest = { parentId: string | null; name: string };

/**
 * Returns the newly created directory node.
 */
export type CreateDirResponse = { node: NodeView };

/**
 * Fields required to create a new file node.
 */
export type CreateFileRequest = {
  parentId: string | null;
  name: string;
  size: bigint | null;
  mimeType: string | null;
};

/**
 * Returns the newly created file node.
 */
export type CreateFileResponse = { node: NodeView };

/**
 * Returns a single node looked up by id or path.
 */
export type GetNodeResponse = { node: NodeView };

/**
 * Returns the virtual path of a node.
 */
export type GetPathResponse = { path: string };

/**
 * Returns the direct children of a directory.
 */
export type ListChildrenResponse = { nodes: Array<NodeView> };

/**
 * Fields required to move or rename a node.
 */
export type MoveNodeRequest = { newParentId: string | null; newName: string };

/**
 * Returns the node after a successful move or rename.
 */
export type MoveNodeResponse = { node: NodeView };

/**
 * Public representation of a VFS node shared across all node responses.
 */
export type NodeView = {
  id: string;
  parentId: string | null;
  name: string;
  /**
   * `"directory"` or `"file"`.
   */
  kind: string;
  size: bigint | null;
  mimeType: string | null;
  createdAt: bigint;
  updatedAt: bigint;
  serverVersion: bigint;
};
