// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields required to create a new directory node.
 */
export type CreateDirRequest = { parentId: string | null; name: string };

/**
 * Returns the newly created directory node.
 */
export type CreateDirResponse = { node: NodeView };

/**
 * Fields required to create a new file node.
 */
export type CreateFileRequest = {
  parentId: string | null;
  name: string;
  size: bigint | null;
  mimeType: string | null;
};

/**
 * Returns the newly created file node.
 */
export type CreateFileResponse = { node: NodeView };

/**
 * Frontend SDK request for soft-deleting a node.
 */
export type DeleteNodeRequest = { id: string };

/**
 * Frontend SDK request for fetching a single node by id.
 */
export type GetNodeByIdRequest = { id: string };

/**
 * Frontend SDK request for resolving a virtual path to a node.
 */
export type GetNodeByPathRequest = { path: string };

/**
 * Frontend SDK request for resolving the full virtual path of a node.
 */
export type GetNodePathRequest = { id: string };

/**
 * Returns a single node looked up by id or path.
 */
export type GetNodeResponse = { node: NodeView };

/**
 * Returns the virtual path of a node.
 */
export type GetPathResponse = { path: string };

/**
 * Frontend SDK request for listing the direct children of a directory.
 */
export type ListChildrenRequest = { id: string };

/**
 * Returns the direct children of a directory.
 */
export type ListChildrenResponse = { nodes: Array<NodeView> };

/**
 * Frontend SDK request for listing root-level nodes (no parameters required).
 */
export type ListRootChildrenRequest = Record<symbol, never>;

/**
 * Fields required to move or rename a node.
 */
export type MoveNodeRequest = { newParentId: string | null; newName: string };

/**
 * Returns the node after a successful move or rename.
 */
export type MoveNodeResponse = { node: NodeView };

/**
 * Frontend SDK request for move/rename: combines the path-level node id with the body fields.
 *
 * Defined separately from [`MoveNodeRequest`] so the SDK caller passes a single flat object
 * instead of composing the id and body separately.
 */
export type MoveNodeWithIdRequest = {
  id: string;
  newParentId: string | null;
  newName: string;
};

/**
 * Frontend SDK request for checking whether a node exists at a virtual path.
 */
export type NodeExistsRequest = { path: string };

/**
 * Public representation of a VFS node shared across all node responses.
 */
export type NodeView = {
  id: string;
  parentId: string | null;
  name: string;
  /**
   * `"directory"` or `"file"`.
   */
  kind: string;
  size: bigint | null;
  mimeType: string | null;
  createdAt: bigint;
  updatedAt: bigint;
};
