services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /workspaces/volumes/cloudbeaver:/opt/cloudbeaver/workspace
  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /workspaces/volumes/postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: 1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onlyquant -d only"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=onlyquant
      - POSTGRES_DB=sonora
