name: Build and Push Sonora Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag (e.g., 1.2.3)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set lowercase owner
        env:
          OWNER: ${{ github.repository_owner }}
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Triggered by tag push (remove 'v' prefix)
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # Triggered by manual workflow dispatch
            VERSION="${{ github.event.inputs.version }}"
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Building release version: ${VERSION}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/sonora:${{ env.VERSION }}
